# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ae0bc1866fe4bd1e47f1ce3ec360232cb3980cd15dbac40a999d9539bbe59beb8d051166c95cec093cacec86b269e2f2e8c4105add0ce4bf79957b08f68c7b4

test:
  secret_key_base: a6c3c7c47bf256036a180b3f6c89cd9d60137ccc045a51e4a01e076992989b4fdc2f9fc1ae704d12c743bb920ef4a78f6b920c14de50fc06d364749c4831620e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
